### PR TITLE
feat: add branch name to payload

### LINKED ISSUE #19: Add branch information
It would be awesome if we could add the git branch we're working on into the heartbeat. I find it useful as it can give hints of what task you're working on inside a project.

Thanks for maintaining the watcher :)

### PR DESCRIPTION
**Pull request by FilipHarald**
Fixes #19

### CODE REVIEW

**Comment by FilipHarald** [comment]
#19

**Review by ErikBjare — APPROVED** [review]
Hi @FilipHarald, good to see you here, and thanks for the contribution!

Looks good! Merging.

**Comment by FilipHarald** [comment]
Hello! Nice to be here :)

Perfect, thank you.

**Comment by johan-bjareholt** [comment]
The branch detection is syncronous and could potentially slow down VIM significantly.
I think we should consider reverting this change. See https://github.com/ActivityWatch/aw-watcher-vim/issues/26

**Comment by FilipHarald** [comment]
> The branch detection is syncronous and could potentially slow down VIM significantly. I think we should consider reverting this change. See #26

It's up to you what you want to do with the current change. I'll look at improving it: https://github.com/ActivityWatch/aw-watcher-vim/issues/26#issuecomment-1125684727

**Comment by johan-bjareholt** [comment]
@FilipHarald We'll keep it for a few days. If you don't have time to fix it soon, we can revert it and take it in again once it's ready without any hurry!

**Comment by ErikBjare** [comment]
Looks like I was a bit too eager to merge here. Should probably both be done async and with some cache to avoid calling more than every x seconds (maybe ~5s?).

I reverted the PR, will await a new one @FilipHarald :)

Edit: I now noticed @johan-bjareholt mentioned caching too https://github.com/ActivityWatch/aw-watcher-vim/issues/26#issuecomment-1125375643

**Pull request merged**
